- name: patch openshift-ansible
  hosts: masters[0]
  gather_facts: false
  roles:
    - openshift_ansible_patches
  tags:
    - openshift_ansible_patches

- name: install openshift master extensions
  hosts: masters
  gather_facts: false
  roles:
    - openshift_master_extensions
  tags:
    - openshift_master_extensions

- name: cache images locally and upload them to all servers
  hosts: all
  gather_facts: false
  roles:
    - cache-images

- hosts: all
  gather_facts: false
  tasks:
    - name: install redhat certs for docker registry
      yum: name=python-rhsm-certificates

    - name: add openshift bin dir to system-wide $PATH for cli usage
      copy:
        dest: /etc/profile.d/openshift-path.sh
        content: 'PATH=$PATH:/usr/local/bin'

- import_playbook: openshift-ansible/playbooks/byo/config.yml
